# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Linter(Python)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  lint:
    runs-on: ubuntu-latest
    container: lwinmgmg/odoo:17.0
    steps:
    - name: Code Checkout
      uses: actions/checkout@v3
    - name: Installation
      run: pip install -r requirements-dev.txt
    - name: Pylint Linter
      run: pylint --rcfile=.pylintrc --init-hook="import sys; sys.path.append('${ODOO_INSTALL_DIR}')" .
